window.PreviewCatalog = [
  { id: 'R01', category: '结果页面', title: '号码级 · 部分领取', description: '已领2张券，认证与绑车待解锁活动分别分组，认证在前。', steps: '直接看结果；可点击去认证或去绑车。', scene: 'grouped-preview', route: 'result' },
  { id: 'R02', category: '结果页面', title: '绑车级 · 已领活动折叠', description: '已领7张券；保留首个中奖活动，其他两个已领活动默认收起。', steps: '展开其他已领活动，再体验单活动查看更多和收起。', scene: 'folded-preview', route: 'result' },
  { id: 'R03', category: '结果页面', title: '全部子活动等级不满足', description: '号码级用户0张领取，全部4个子活动人群匹配，但需绑车或认证。', steps: '查看中性零领取提示与两组待解锁卡券。', scene: 'all-locked-preview', route: 'result' },
  { id: 'R04', category: '结果页面', title: '认证级 · 全部可领结果', description: '有效直领券与中奖券共8张；未中奖活动不展示，过期券不发放。', steps: '展开其他已领活动，确认无等级升级引导。', scene: 'verified-result-preview', route: 'result' },
  { id: 'R05', category: '结果页面', title: '人群均不匹配 · 无可参与活动', description: '即使已认证，人群不匹配仍不可参与；不发券、不展示升级即领承诺。', steps: '查看空结果与底部领券中心入口。', scene: 'no-eligible-preview', route: 'result' },
  { id: 'R06', category: '结果页面', title: '单活动券排序与展开', description: '未领取在前，已领可用其次，过期在后；已领券没有激活操作。', steps: '先展开其他活动，再展开秋日安心养护礼的5张券。', scene: 'coupon-states', route: 'result' },
  { id: 'R07', category: '结果页面', title: '未解锁券 · 配置图片适配', description: '演示配置券图原样显示，待解锁按钮在图片外，不压灰、不加遮罩。', steps: '在认证分组查看蓝色示例券图；图片仅用于展示比例与布局。', scene: 'artwork-preview', route: 'result' },
  { id: 'F01', category: '参与流程', title: '活动政策与完整参与流程', description: '配置素材及链接展示，立即参与位于KV后；点击才开始资格判断。', steps: '立即参与 → 独立抽奖 → 查看领取结果。', scene: 'bound-lottery', route: 'activity' },
  { id: 'F02', category: '参与流程', title: '未登录 · 登录后继续', description: '参与前先登录，登录成功后继续等级、人群与抽奖判断。', steps: '立即参与 → 登录 → 抽奖 → 查看结果。', scene: 'guest-login', route: 'activity' },
  { id: 'F03', category: '参与流程', title: '号码级 · 直接领取后升级', description: '符合条件的号码级券先发放，等级不足项留在结果页。', steps: '立即参与 → 去绑车或去认证 → 返回后手动再次参与。', scene: 'number-partial', route: 'activity' },
  { id: 'F04', category: '参与流程', title: '号码级 · 零领取及未开始活动', description: '当前可参与项为0；较高等级活动与尚未开始的活动分别显示。', steps: '立即参与后查看零领取、等级分组与未开始倒计时。', scene: 'number-zero', route: 'activity' },
  { id: 'F05', category: '参与流程', title: '认证级 · 多个独立抽奖', description: '符合条件且未参加的两个抽奖依次进入，不以首次点击组合为限制。', steps: '立即参与 → 第一次中奖 → 继续第二次未中奖 → 查看结果。', scene: 'verified-all', route: 'activity' },
  { id: 'F06', category: '参与流程', title: '重复参与 · 已抽奖不重抽', description: '已参加抽奖的记录保留；再次参与不重抽、不重复发已领券。', steps: '立即参与，直接进入领取结果。', scene: 'bound-repeat', route: 'activity' },
  { id: 'F07', category: '参与流程', title: '认证级 · 部分人群不匹配', description: '认证等级不能绕过人群限制，仅保留人群符合的活动。', steps: '立即参与，查看只包含匹配活动的结果。', scene: 'audience-miss', route: 'activity' },
  { id: 'L01', category: '抽奖分支', title: '待抽奖页面', description: '已通过参与条件，直领券已发放，当前抽奖尚未参加。', steps: '立即抽奖 → 中奖页 → 查看我的好礼。', scene: 'lottery-ready-preview', route: 'lottery' },
  { id: 'L02', category: '抽奖分支', title: '中奖结果页面', description: '展示已中奖奖券；进入领取结果后中奖活动排在其他活动前。', steps: '点击查看我的好礼。', scene: 'lottery-won-preview', route: 'lottery' },
  { id: 'L03', category: '抽奖分支', title: '未中奖结果页面', description: '未中奖页保留参与反馈；进入领取结果后不再展示该抽奖券。', steps: '点击查看我的好礼，查看其他已领取的直领券。', scene: 'lottery-lost-preview', route: 'lottery' },
  { id: 'U01', category: '等级操作', title: '绑定车辆及返回', description: '绑定仅提升参与资格，不在升级完成时自动补发。', steps: '完成并返回活动 → 手动立即参与 → 查看新增可领券。', scene: 'bind-preview', route: 'upgrade' },
  { id: 'U02', category: '等级操作', title: '车主认证及返回', description: '完成认证后可参与更高等级活动，抽奖奖品仍按抽奖结果。', steps: '完成并返回活动 → 手动立即参与 → 进入未参加的抽奖。', scene: 'certify-preview', route: 'upgrade' },
  { id: 'T01', category: '时间与异常', title: '组合活动尚未开始', description: '展示“活动暂未开启，感谢关注！”，不进入登录、抽奖或发券。', steps: '直接查看时间门禁提示。', scene: 'combo-upcoming', route: 'activity' },
  { id: 'T02', category: '时间与异常', title: '组合活动已结束', description: '展示“活动已结束，感谢关注！”，停止参与。', steps: '直接查看结束提示。', scene: 'combo-ended', route: 'activity' },
  { id: 'T03', category: '时间与异常', title: '子活动未开始与倒计时', description: '组合进行中，但个别子活动尚未开始；领取结果里禁用其按钮。', steps: '向下滚动至更多活动，查看活动未开始和倒计时。', scene: 'folded-preview', route: 'result' },
  { id: 'T04', category: '时间与异常', title: '卡券已过期', description: '过期属于卡券，不单独展示已过期活动；券留在所属活动末尾。', steps: '展开其他已领活动及单活动查看更多，查看灰色已过期按钮。', scene: 'coupon-states', route: 'result' },
  { id: 'T05', category: '时间与异常', title: '资格核验异常结果', description: '核验异常不猜测用户等级，也不抽奖或发券，提供重试。', steps: '查看暂时无法核验，点击重新校验体验恢复。', scene: 'context-error-preview', route: 'result' },
  { id: 'T06', category: '时间与异常', title: '资格异常完整流程', description: '从政策页点击参与后进入异常提示，可重新核验。', steps: '立即参与 → 异常 → 重新校验 → 后续参与。', scene: 'level-error', route: 'activity' },
  { id: 'J01', category: '跳转', title: '领券中心跳转演示', description: '结果末尾查看更多优惠券进入此页；正式领券中心地址尚未接入。', steps: '查看演示页，再点顶部返回，原领取状态保留。', scene: 'folded-preview', route: 'coupon-center' }
];
