(function(){
  'use strict';
  var data=window.StateBoardData||{sections:[],nodes:[],edges:[]};
  var manifest=window.ScreenManifest||{};
  var viewport=document.getElementById('viewport'),world=document.getElementById('world');
  var nodesHost=document.getElementById('nodes'),sectionHost=document.getElementById('sections');
  var svg=document.getElementById('connections'),nav=document.getElementById('section-nav');
  var list=document.getElementById('page-list'),search=document.getElementById('search');
  var NS='http://www.w3.org/2000/svg',HEAD=100,MIN=.035,MAX=1.8;
  var camera={x:50,y:30,scale:.5},selected=null,activeSection=null,pointers=new Map(),gesture=null,renderFrame=0;
  var nodeMap=new Map(),sectionMap=new Map(),edgeGeometry=[];
  function el(tag,className,text){var n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;}
  function sEl(tag,attrs){var n=document.createElementNS(NS,tag);Object.keys(attrs||{}).forEach(function(k){n.setAttribute(k,attrs[k]);});return n;}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
  function nodeHeight(n){var m=manifest[n.screenId];if(n.type==='screen'&&m)return HEAD+m.height*n.width/m.width;return n.height||(n.type==='dialog'?260:n.type==='decision'?180:n.type==='note'?160:650);}
  function pageGroup(n){var group=sectionMap.get(n.sectionId);return group?(group.shortTitle||group.title):'页面状态';}
  function getNode(id){return nodeMap.get(id);}
  function rectOf(n){return{x:n.x,y:n.y,width:n.width,height:n.height};}
  function union(rects){if(!rects.length)return{x:0,y:0,width:1500,height:900};var x=Math.min.apply(null,rects.map(function(r){return r.x;})),y=Math.min.apply(null,rects.map(function(r){return r.y;}));return{x:x,y:y,width:Math.max.apply(null,rects.map(function(r){return r.x+r.width;}))-x,height:Math.max.apply(null,rects.map(function(r){return r.y+r.height;}))-y};}
  data.nodes.forEach(function(raw){var n=Object.assign({},raw,{height:nodeHeight(raw)});nodeMap.set(n.id,n);});
  data.sections.forEach(function(section){sectionMap.set(section.id,section);var box=el('section','board-section');box.dataset.sectionId=section.id;box.style.cssText='left:'+section.x+'px;top:'+section.y+'px;width:'+section.width+'px;height:'+section.height+'px';var caption=el('div','section-caption');caption.append(el('h2','',section.title),el('p','',section.subtitle||''));box.append(caption);sectionHost.append(box);var button=el('button','',section.shortTitle||section.title);button.dataset.sectionId=section.id;button.addEventListener('click',function(){focusSection(section.id);});nav.append(button);});
  nodeMap.forEach(function(n){var card=el('article','state-node '+n.type+(n.emphasis?' emphasis':''));card.dataset.nodeId=n.id;card.style.cssText='left:'+n.x+'px;top:'+n.y+'px;width:'+n.width+'px;height:'+n.height+'px';card.setAttribute('aria-label',n.title);if(n.type==='screen'||n.type==='dialog'){var header=el('div','node-header');header.append(el('div','node-code',pageGroup(n)),el('h3','',n.title),el('p','',n.description||''));card.append(header);if(n.type==='dialog'){var surface=el('div','dialog-surface');surface.append(el('p','dialog-message','您尚未登录，请登录后参与活动'));var actions=el('div','dialog-actions');actions.append(el('span','dialog-action secondary','取消'),el('span','dialog-action primary','去登录'));surface.append(actions);card.append(surface);}else{var m=manifest[n.screenId];if(m){var img=el('img');img.src=m.src;img.alt=n.title;img.draggable=false;img.width=m.width;img.height=m.height;img.decoding='async';card.append(img);}else{card.append(el('div','image-missing','该页面截图待补充'));}}}else if(n.type==='decision'){var diamond=sEl('svg',{class:'decision-shape',viewBox:'0 0 '+n.width+' '+n.height,'aria-hidden':'true'});diamond.append(sEl('polygon',{points:(n.width/2)+',0 '+n.width+','+(n.height/2)+' '+(n.width/2)+','+n.height+' 0,'+(n.height/2)}));var copy=el('div','decision-content');copy.append(el('h3','',n.title),el('p','',n.description||''));card.append(diamond,copy);}else{card.append(el('h3','',n.title),el('p','',n.description||''));}nodesHost.append(card);n.element=card;});
  function anchor(n,side,ratio){ratio=typeof ratio==='number'?ratio:.5;var r=rectOf(n);if(side==='left')return{x:r.x,y:r.y+r.height*ratio};if(side==='top')return{x:r.x+r.width*ratio,y:r.y};if(side==='bottom')return{x:r.x+r.width*ratio,y:r.y+r.height};return{x:r.x+r.width,y:r.y+r.height*ratio};}
  function route(edge){var from=getNode(edge.from)||sectionMap.get(edge.from),to=getNode(edge.to)||sectionMap.get(edge.to);if(!from||!to)return null;var fs=edge.fromSide||'right',ts=edge.toSide||'left',a=anchor(from,fs,edge.fromRatio),b=anchor(to,ts,edge.toRatio);if(edge.points&&edge.points.length)return[a].concat(edge.points,[b]);var points=[a];if((fs==='left'||fs==='right')&&(ts==='left'||ts==='right')){var mx=(a.x+b.x)/2;points.push({x:mx,y:a.y},{x:mx,y:b.y});}else if((fs==='top'||fs==='bottom')&&(ts==='top'||ts==='bottom')){var my=(a.y+b.y)/2;points.push({x:a.x,y:my},{x:b.x,y:my});}else if(fs==='left'||fs==='right'){points.push({x:b.x,y:a.y});}else{points.push({x:a.x,y:b.y});}points.push(b);return points;}
  function midpoint(points){var best={length:-1,x:0,y:0};for(var i=1;i<points.length;i++){var a=points[i-1],b=points[i],len=Math.hypot(b.x-a.x,b.y-a.y);if(len>best.length)best={length:len,x:(a.x+b.x)/2,y:(a.y+b.y)/2};}return best;}
  var defs=sEl('defs');['flow','detail','return'].forEach(function(kind){var marker=sEl('marker',{id:'arrow-'+kind,viewBox:'0 0 12 12',refX:10,refY:6,markerWidth:9,markerHeight:9,orient:'auto',markerUnits:'userSpaceOnUse'});marker.append(sEl('path',{d:'M 1 1 L 11 6 L 1 11 Z',fill:kind==='return'?'#a85b4e':kind==='detail'?'#7c8793':'#5c6673'}));defs.append(marker);});svg.append(defs);
  data.edges.forEach(function(edge){var points=route(edge);if(!points)return;var kind=edge.kind||'flow',g=sEl('g',{'data-edge-id':edge.id,'data-from':edge.from,'data-to':edge.to});var path=sEl('path',{class:'edge-path '+kind,d:points.map(function(p,i){return(i?'L':'M')+p.x+' '+p.y;}).join(' '),'marker-end':'url(#arrow-'+kind+')'});g.append(path);edgeGeometry.push({id:edge.id,from:edge.from,to:edge.to,points:points});if(edge.label){var middle=midpoint(points),x=typeof edge.labelX==='number'?edge.labelX:middle.x,y=typeof edge.labelY==='number'?edge.labelY:middle.y;var lines=String(edge.label).split('\n');var w=Math.max.apply(null,lines.map(function(t){return Array.from(t).reduce(function(total,ch){return total+(ch.charCodeAt(0)>255?15:8);},0);}))+22,h=lines.length*22+8;var label=sEl('g',{class:'edge-label '+kind,transform:'translate('+x+' '+y+')'});label.append(sEl('rect',{x:-w/2,y:-h/2,width:w,height:h}));var text=sEl('text');lines.forEach(function(line,i){var span=sEl('tspan',{x:0,y:(i-(lines.length-1)/2)*22});span.textContent=line;text.append(span);});label.append(text);g.append(label);}svg.append(g);});
  var bounds=union(data.sections.length?data.sections:Array.from(nodeMap.values()).map(rectOf));svg.setAttribute('width',Math.max(bounds.x+bounds.width,1));svg.setAttribute('height',Math.max(bounds.y+bounds.height,1));
  function render(){renderFrame=0;world.style.transform='translate('+camera.x+'px,'+camera.y+'px) scale('+camera.scale+')';viewport.style.backgroundSize=Math.max(16,20*camera.scale)+'px '+Math.max(16,20*camera.scale)+'px';viewport.style.backgroundPosition=camera.x+'px '+camera.y+'px';document.getElementById('zoom-reset').textContent=Math.round(camera.scale*100)+'%';document.getElementById('status').textContent=data.nodes.filter(function(n){return n.type==='screen'||n.type==='dialog';}).length+' 个页面状态 · '+data.edges.length+' 条连线';}
  function schedule(){if(!renderFrame)renderFrame=requestAnimationFrame(render);}
  function setCamera(x,y,scale){camera.x=x;camera.y=y;camera.scale=clamp(scale,MIN,MAX);schedule();}
  function fitRect(rect,maxScale){var w=viewport.clientWidth,h=viewport.clientHeight,pad=Math.min(60,w*.06),scale=clamp(Math.min((w-2*pad)/rect.width,(h-2*pad-38)/rect.height,maxScale||1),MIN,MAX);setCamera((w-rect.width*scale)/2-rect.x*scale,(h-38-rect.height*scale)/2-rect.y*scale,scale);}
  function selectNode(id){if(selected&&getNode(selected))getNode(selected).element.classList.remove('selected');selected=id;var n=getNode(id);if(n)n.element.classList.add('selected');}
  function setActiveSection(id){activeSection=id;nav.querySelectorAll('button').forEach(function(b){b.classList.toggle('active',b.dataset.sectionId===id);});}
  function focusNode(id,options){var n=getNode(id);if(!n)return false;selectNode(id);setActiveSection(n.sectionId);options=options||{};if(options.full)fitRect(rectOf(n),1);else{var w=viewport.clientWidth,h=viewport.clientHeight,scale=Math.min(options.scale||1,(w-56)/n.width);scale=clamp(scale,MIN,MAX);setCamera((w-n.width*scale)/2-n.x*scale,30-n.y*scale,scale);}closeList();return true;}
  function focusSection(id){var section=sectionMap.get(id);if(!section)return false;selectNode(null);setActiveSection(id);fitRect(section,.72);closeList();return true;}
  function fitAll(){selectNode(null);setActiveSection(null);fitRect(bounds,.65);closeList();}
  function zoomAt(scale,x,y){scale=clamp(scale,MIN,MAX);var wx=(x-camera.x)/camera.scale,wy=(y-camera.y)/camera.scale;setCamera(x-wx*scale,y-wy*scale,scale);}
  function centerZoom(factor){zoomAt(camera.scale*factor,viewport.clientWidth/2,viewport.clientHeight/2);}
  function point(event){var r=viewport.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top};}
  viewport.addEventListener('wheel',function(event){event.preventDefault();var p=point(event);zoomAt(camera.scale*Math.exp(-event.deltaY*.0015),p.x,p.y);},{passive:false});
  function gestureStart(){var ps=Array.from(pointers.values());if(ps.length===1)gesture={type:'pan',p:ps[0],x:camera.x,y:camera.y};else if(ps.length>=2){var a=ps[0],b=ps[1];gesture={type:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),scale:camera.scale,mid:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},x:camera.x,y:camera.y};}else gesture=null;}
  viewport.addEventListener('pointerdown',function(event){if(event.button!==0&&event.pointerType==='mouse')return;pointers.set(event.pointerId,point(event));viewport.setPointerCapture(event.pointerId);viewport.classList.add('dragging');gestureStart();event.preventDefault();});
  viewport.addEventListener('pointermove',function(event){if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,point(event));var ps=Array.from(pointers.values());if(!gesture)return;if(gesture.type==='pan'&&ps.length===1){setCamera(gesture.x+ps[0].x-gesture.p.x,gesture.y+ps[0].y-gesture.p.y,camera.scale);}else if(gesture.type==='pinch'&&ps.length>=2){var a=ps[0],b=ps[1],scale=clamp(gesture.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(gesture.distance,1),MIN,MAX),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};setCamera(mid.x-(gesture.mid.x-gesture.x)/gesture.scale*scale,mid.y-(gesture.mid.y-gesture.y)/gesture.scale*scale,scale);}});
  function release(event){pointers.delete(event.pointerId);gestureStart();if(!pointers.size)viewport.classList.remove('dragging');}
  viewport.addEventListener('pointerup',release);viewport.addEventListener('pointercancel',release);viewport.addEventListener('lostpointercapture',release);
  document.getElementById('zoom-in').addEventListener('click',function(){centerZoom(1.25);});document.getElementById('zoom-out').addEventListener('click',function(){centerZoom(.8);});document.getElementById('zoom-reset').addEventListener('click',function(){zoomAt(1,viewport.clientWidth/2,viewport.clientHeight/2);});document.getElementById('fit-all').addEventListener('click',fitAll);
  function closeList(){list.hidden=true;document.getElementById('list-toggle').setAttribute('aria-expanded','false');}
  function openList(){list.hidden=false;document.getElementById('list-toggle').setAttribute('aria-expanded','true');search.focus();}
  document.getElementById('list-toggle').addEventListener('click',function(){if(list.hidden)openList();else closeList();});document.getElementById('list-close').addEventListener('click',closeList);
  function renderList(){var q=search.value.trim().toLowerCase(),host=document.getElementById('search-results');host.replaceChildren();var found=0;data.sections.forEach(function(section){var group=data.nodes.filter(function(n){return n.sectionId===section.id&&(n.type==='screen'||n.type==='dialog')&&(!q||[n.title,n.description,pageGroup(n)].join(' ').toLowerCase().indexOf(q)>=0);});if(!group.length)return;host.append(el('div','result-group-label',section.title));group.forEach(function(n){found++;var button=el('button','result-item',n.title);button.append(el('small','',pageGroup(n)));button.addEventListener('click',function(){focusNode(n.id);});host.append(button);});});if(!found)host.append(el('div','no-results','没有匹配的页面'));}
  search.addEventListener('input',renderList);renderList();
  window.addEventListener('keydown',function(event){if(event.key==='Escape'){closeList();return;}if(event.target.matches('input,textarea'))return;if(event.key==='+'||event.key==='='){event.preventDefault();centerZoom(1.25);}if(event.key==='-'){event.preventDefault();centerZoom(.8);}if(event.key==='0'){event.preventDefault();fitAll();}});
  window.addEventListener('resize',schedule);
  window.StateBoard={focusNode:focusNode,focusSection:focusSection,fitAll:fitAll,getState:function(){return{camera:Object.assign({},camera),selectedNode:selected,activeSection:activeSection,nodeCount:nodeMap.size,edgeCount:edgeGeometry.length,bounds:Object.assign({},bounds),nodes:Array.from(nodeMap.values()).map(function(n){return{id:n.id,x:n.x,y:n.y,width:n.width,height:n.height,type:n.type,screenId:n.screenId};}),edges:edgeGeometry,headHeight:HEAD};}};
  document.getElementById('empty').hidden=data.nodes.length>0;
  var requested=new URLSearchParams(location.search).get('node');if(requested&&focusNode(requested)){}else if(data.initialView){fitRect(data.initialView,data.initialView.maxScale||.7);}else if(data.sections.length){var first=data.sections[0];setActiveSection(first.id);fitRect({x:first.x,y:first.y,width:Math.min(first.width,1900),height:Math.min(first.height,1300)},.7);}else fitAll();render();
})();
