(function(){
  'use strict';
  const $=s=>document.querySelector(s);
  const couponRules=[
    {title:'领取规则不符：直接过滤',when:['准入等级＝号码级','领取规则≠用户（含 VIN、空值或未知值）'],then:'卡券中心不返回该券；选择列表不展示，不可勾选、不可关联。无论卡券属于哪个业务场景，都先执行本条。'},
    {title:'BIMC（新）：用户＋线上核销',when:['准入等级＝号码级','卡券业务场景＝售后营销 / BIMC（新）','领取规则＝用户','核销方式＝线上核销'],then:'通过本次新增过滤；同时满足原有可关联条件时，卡券中心返回该券，允许勾选并关联。'},
    {title:'维修保养（新）：用户＋线上核销',when:['准入等级＝号码级','卡券业务场景＝售后营销 / 维修保养（新）','领取规则＝用户','核销方式＝线上核销'],then:'通过本次新增过滤；同时满足原有可关联条件时，卡券中心返回该券，允许勾选并关联。'},
    {title:'指定两场景核销方式不符：过滤',when:['准入等级＝号码级','卡券业务场景＝BIMC（新）或维修保养（新）（两者任选其一）','领取规则＝用户','核销方式≠线上核销'],then:'卡券中心不返回该券，不可勾选、不可关联。线下核销、到店核销、线上线下组合、空值或未知值，都不等于“线上核销”。'},
    {title:'其他场景：只追加用户领取限制',when:['准入等级＝号码级','领取规则＝用户','卡券业务场景既不是 BIMC（新），也不是维修保养（新）（如商城营销 / 新商城）'],then:'本次不追加核销方式限制，继续按该场景原有可关联条件返回卡券。例如其他场景的到店核销券，不因本次“线上核销”规则被排除。'},
    {title:'非号码级：沿用原有规则',when:['准入等级≠号码级（如绑车级、认证级）'],then:'本次不追加“领取规则＝用户”或“核销方式＝线上核销”的限制，继续按原有查询与关联规则处理。'}
  ];
  const notes=[
    {id:'N01',step:1,title:'活动类型决定默认值与必填性',selector:'[data-field="trigger"]',field:true,refs:'F11–F13 · R02–R05',text:'C端主动参与活动默认选车，商城周边默认选人。用户行为触发、商城售后和商城周边非必填；商城售后与周边复选只可选交集“选人”。',pending:'默认值不等于额外禁选规则。非号码级C端、商城周边单选的额外禁选范围待确认。'},
    {id:'N02',step:1,title:'准入配置前移并优先限制属性',selector:'#admission-config',refs:'F10、F14 · R01、R07',text:'整个准入配置从step3移到step1，位于活动状态（启停用）上方。号码级只允许选人，覆盖C端默认选车；必填性仍按活动类型独立判断。',pending:'当前沿用C端主动参与活动显示准入配置。是否扩展其他类型待确认。'},
    {id:'N03',step:2,title:'查询条件传递与处理责任',selector:'.summary-strip',refs:'F06、F16 · R08、R09',text:'当准入等级＝号码级时，管理后台把“号码级”和当前选择的卡券业务场景传给活动中心后端，再由后端适配并传给卡券中心。卡券中心按标注4 / 7的条件过滤后返回，管理后台只展示返回结果。搜索、重置、刷新、翻页均保留当前准入等级及其强制过滤条件。',pending:'此处使用页面业务字段名说明规则；正式接口字段名、枚举编码待研发对齐，当前页面使用本地演示数据。'},
    {id:'N04',step:2,title:'关联卡券：字段条件与处理',selector:'.coupon-card',refs:'F01–F03、F09、F17、F18 · R08、R09',text:'以下按每张候选卡券判断；同一条中的“且”必须同时满足。场景指卡券业务场景，不是活动类型。选中后展示领取规则与核销方式，便于核对。',rules:couponRules,pending:'原型建议：当已关联卡券不满足当前条件时（如切换到号码级或恢复旧草稿），保留冲突券并提示，阻止继续和保存，需移除或重新选券。正式清空/保留策略及服务端复核责任待确认。'},
    {id:'N05',step:3,title:'先限制可选范围，再应用默认值',selector:'input[name="attribute"]',field:true,refs:'F11–F14 · R02–R05、R07',text:'属性为单选。号码级仅选人优先，商城复选再取交集，最后应用活动类型默认值。非必填场景仍可清空，“仅选人”不等于必须填写。',pending:'当前商城周边单选的禁选展示沿用原型，是否作为正式限制见待确认Q03。'},
    {id:'N06',step:3,title:'用户标识自动勾选并锁定',selector:'input[aria-label="oneid"],input[aria-label="VIN"]',field:true,fallback:'.form-panel > .field:nth-child(2)',refs:'F15 · R06、R07',text:'选人对应oneid，选车对应VIN，选人+车同时对应oneid与VIN，均不可编辑。两字段为“且”，必须均一致才可发放或领取。属性为空时不残留旧标识。',pending:'真实发放与领取服务仍须联调验证；号码级不代表将主键改成手机号。'},
    {id:'N07',modal:true,title:'选券过滤：字段条件与处理',selector:'.filter-lock',fallback:'.filters',refs:'F01–F03 · R08、R09',text:'按下列条件逐张过滤。BIMC（新）、维修保养（新）是两个场景分支；每个分支内的准入等级、领取规则、核销方式必须同时满足，不是满足其中一项即可。',rules:couponRules},
    {id:'N08',modal:true,title:'搜索、空结果与分页处理',selector:'.block-table',refs:'F04、F05、F07 · R08、R09',text:'当卡券ID或卡券名称填写了搜索值时，只在符合标注7条件的结果内搜索，不得用精确ID绕过过滤。当符合全部适用条件的卡券数量＝0时，列表展示“暂无符合条件的卡券”，不能关联被过滤的券。重置搜索、刷新和翻页不取消号码级强制条件。',pending:'实现建议：卡券中心先执行全部适用条件，再计算总数和分页；不可只在当前页删除不合规行。正式返回字段和空结果格式待确认。'}
  ];
  const drawer=document.createElement('aside');drawer.className='annotation-drawer';drawer.id='annotation-drawer';drawer.setAttribute('aria-label','页面标注');
  drawer.innerHTML='<div class="annotation-heading"><h2>页面标注</h2><button type="button" aria-label="收起页面标注">×</button></div><p class="annotation-intro">对应功能清单 F01–F18。点击编号或“定位字段”查看页面位置。褐色文字为建议或待确认项。</p><nav class="annotation-nav" aria-label="标注步骤导航"></nav><div class="annotation-scroll"></div>';
  const toggle=document.createElement('button');toggle.type='button';toggle.className='annotation-toggle';toggle.textContent='页面标注';toggle.setAttribute('aria-controls',drawer.id);
  const layer=document.createElement('div');layer.className='annotation-pin-layer';document.body.append(toggle,drawer,layer);
  let opened=window.innerWidth>1100,active='',currentNotes=[],raf=0,focusTimer;
  function ruleDetails(rules){return rules?'<ol class="annotation-rules">'+rules.map(r=>'<li><h4>'+r.title+'</h4><div class="annotation-conditions">'+r.when.map((value,i)=>'<p><span class="condition-join">'+(i?'且':'当')+'</span><span>'+value+'</span></p>').join('')+'</div><p class="annotation-outcome"><strong>处理 → </strong>'+r.then+'</p></li>').join('')+'</ol>':'';}
  function target(n){let e=$(n.selector);if(e&&n.field)e=e.closest('.field');return e||(n.fallback?$(n.fallback):null);}
  function context(){const dialog=$('[role="dialog"]');if(dialog&&dialog.getAttribute('aria-label')==='选择卡券')return 'modal';const tab=$('.steps [aria-selected="true"]');return tab?Number(tab.dataset.step):0;}
  function paintPins(){raf=0;layer.replaceChildren();if(!opened)return;for(const n of currentNotes){const e=target(n);if(!e)continue;const r=e.getBoundingClientRect();if(r.width===0||r.bottom<0||r.top>innerHeight)continue;const pin=document.createElement('button');pin.type='button';pin.className='annotation-pin';pin.textContent=String(Number(n.id.slice(1)));pin.setAttribute('aria-label','查看标注'+n.id+' '+n.title);pin.style.left=Math.max(4,r.left-15+scrollX)+'px';pin.style.top=Math.max(scrollY+6,r.top+scrollY+4)+'px';pin.addEventListener('click',()=>locate(n.id,false));layer.append(pin);}}
  function schedule(){if(!raf)raf=requestAnimationFrame(paintPins);}
  function open(v){opened=v;document.body.classList.toggle('annotations-open',v);drawer.hidden=!v;toggle.hidden=v;toggle.setAttribute('aria-expanded',String(v));if(!v){document.querySelectorAll('.annotation-focus').forEach(e=>e.classList.remove('annotation-focus'));toggle.focus({preventScroll:true});}schedule();}
  function locate(id,fromDrawer=true){const n=notes.find(x=>x.id===id);if(!n)return;active=id;document.querySelectorAll('.annotation-note').forEach(x=>x.classList.toggle('is-active',x.dataset.note===id));const e=target(n);if(e){document.querySelectorAll('.annotation-focus').forEach(x=>x.classList.remove('annotation-focus'));e.classList.add('annotation-focus');if(fromDrawer){if(innerWidth<=1100)open(false);e.scrollIntoView({behavior:'smooth',block:'center'});e.classList.add('annotation-focus');}clearTimeout(focusTimer);focusTimer=setTimeout(()=>e.classList.remove('annotation-focus'),4500);}if(!fromDrawer){drawer.querySelector('[data-note="'+id+'"]').scrollIntoView({behavior:'smooth',block:'nearest'});}schedule();}
  function render(){const c=context();currentNotes=notes.filter(n=>c==='modal'?n.modal:n.step===c).filter(n=>target(n));const nav=drawer.querySelector('.annotation-nav');nav.innerHTML=[1,2,3].map(s=>'<button type="button" data-note-step="'+s+'" class="'+(c===s?'active':'')+'">step'+s+'</button>').join('');nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(c==='modal'){const close=$('[data-action="close-modal"]');if(close)close.click();}const tab=$('.steps [data-step="'+b.dataset.noteStep+'"]');if(tab)tab.click();}));
    drawer.querySelector('.annotation-scroll').innerHTML='<p class="annotation-context">'+(c==='modal'?'选择卡券弹窗':c?'step'+c+' 的变更说明':'当前页面')+'</p>'+(currentNotes.length?currentNotes.map(n=>'<section class="annotation-note '+(active===n.id?'is-active':'')+'" data-note="'+n.id+'"><h3><span class="number">'+Number(n.id.slice(1))+'</span>'+n.title+'</h3><p class="refs">'+n.refs+'</p><p>'+n.text+'</p>'+ruleDetails(n.rules)+(n.pending?'<p class="pending">'+n.pending+'</p>':'')+'<button type="button" data-locate="'+n.id+'">定位字段</button></section>').join(''):'<p class="annotation-empty">本次调整集中在step1至step3。可用上方导航查看对应标注。</p>');drawer.querySelectorAll('[data-locate]').forEach(b=>b.addEventListener('click',()=>locate(b.dataset.locate)));schedule();}
  toggle.addEventListener('click',()=>{open(true);render();drawer.querySelector('button').focus({preventScroll:true});});drawer.querySelector('.annotation-heading button').addEventListener('click',()=>open(false));drawer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();open(false);}});
  new MutationObserver(render).observe($('#main'),{childList:true,subtree:true});new MutationObserver(render).observe($('#modal-root'),{childList:true,subtree:true});window.addEventListener('scroll',schedule,true);window.addEventListener('resize',schedule);open(opened);render();
})();
