(function(){
  'use strict';
  const $=s=>document.querySelector(s);
  const notes=[
    {id:'N01',step:1,title:'活动类型决定默认值与必填性',selector:'[data-field="trigger"]',field:true,refs:'F11–F13 · R02–R05',text:'C端主动参与活动默认选车，商城周边默认选人。用户行为触发、商城售后和商城周边非必填；商城售后与周边复选只可选交集“选人”。',pending:'默认值不等于额外禁选规则。非号码级C端、商城周边单选的额外禁选范围待确认。'},
    {id:'N02',step:1,title:'准入配置前移并优先限制属性',selector:'#admission-config',refs:'F10、F14 · R01、R07',text:'整个准入配置从step3移到step1，位于活动状态（启停用）上方。号码级只允许选人，覆盖C端默认选车；必填性仍按活动类型独立判断。',pending:'当前沿用C端主动参与活动显示准入配置。是否扩展其他类型待确认。'},
    {id:'N03',step:2,title:'当前准入随查询传给后端',selector:'.summary-strip',refs:'F06、F16 · R08、R09',text:'选择卡券时，管理后台传递当前准入等级和业务场景，活动中心后端适配卡券中心接口。搜索、重置、刷新和翻页继续保留准入条件。',pending:'正式接口字段和枚举待研发对齐；当前页面使用本地演示数据。'},
    {id:'N04',step:2,title:'关联结果与不兼容卡券',selector:'.coupon-card',refs:'F09、F17、F18 · R08、R09',text:'号码级仅允许用户规则券。BIMC（新）、维修保养（新）还须恰为线上核销。选中后展示领取规则与核销方式，便于核对。',pending:'原型建议：切换等级或恢复旧草稿后保留冲突券并提示，阻止继续和保存。正式清空/保留策略及服务端复核责任待确认。'},
    {id:'N05',step:3,title:'先限制可选范围，再应用默认值',selector:'input[name="attribute"]',field:true,refs:'F11–F14 · R02–R05、R07',text:'属性为单选。号码级仅选人优先，商城复选再取交集，最后应用活动类型默认值。非必填场景仍可清空，“仅选人”不等于必须填写。',pending:'当前商城周边单选的禁选展示沿用原型，是否作为正式限制见待确认Q03。'},
    {id:'N06',step:3,title:'用户标识自动勾选并锁定',selector:'input[aria-label="oneid"],input[aria-label="VIN"]',field:true,fallback:'.form-panel > .field:nth-child(2)',refs:'F15 · R06、R07',text:'选人对应oneid，选车对应VIN，选人+车同时对应oneid与VIN，均不可编辑。两字段为“且”，必须均一致才可发放或领取。属性为空时不残留旧标识。',pending:'真实发放与领取服务仍须联调验证；号码级不代表将主键改成手机号。'},
    {id:'N07',modal:true,title:'卡券中心按场景执行两层过滤',selector:'.filter-lock',fallback:'.filters',refs:'F01–F03 · R08、R09',text:'号码级全部场景先要求领取规则=用户。场景为BIMC（新）或维修保养（新）时，再要求核销方式=线上核销，两个条件为“且”。线下、到店、线上线下组合及缺失/未知核销方式均不满足这两类场景的精确匹配。',pending:'其他场景和非号码级继续执行既有规则，不扩大本次核销限制。'},
    {id:'N08',modal:true,title:'过滤结果决定列表、总数和分页',selector:'.block-table',refs:'F04、F05、F07 · R08、R09',text:'活动中心展示卡券中心返回的合规结果。按券ID或名称搜索不能绕过准入限制。',pending:'实现建议：卡券中心先执行全部适用条件，再计算总数和分页；不可只在当前页删除不合规行。正式返回字段和空结果格式待确认。'}
  ];
  const drawer=document.createElement('aside');drawer.className='annotation-drawer';drawer.id='annotation-drawer';drawer.setAttribute('aria-label','页面标注');
  drawer.innerHTML='<div class="annotation-heading"><h2>页面标注</h2><button type="button" aria-label="收起页面标注">×</button></div><p class="annotation-intro">对应功能清单 F01–F18。点击编号或“定位字段”查看页面位置。褐色文字为建议或待确认项。</p><nav class="annotation-nav" aria-label="标注步骤导航"></nav><div class="annotation-scroll"></div>';
  const toggle=document.createElement('button');toggle.type='button';toggle.className='annotation-toggle';toggle.textContent='页面标注';toggle.setAttribute('aria-controls',drawer.id);
  const layer=document.createElement('div');layer.className='annotation-pin-layer';document.body.append(toggle,drawer,layer);
  let opened=window.innerWidth>1100,active='',currentNotes=[],raf=0,focusTimer;
  function target(n){let e=$(n.selector);if(e&&n.field)e=e.closest('.field');return e||(n.fallback?$(n.fallback):null);}
  function context(){const dialog=$('[role="dialog"]');if(dialog&&dialog.getAttribute('aria-label')==='选择卡券')return 'modal';const tab=$('.steps [aria-selected="true"]');return tab?Number(tab.dataset.step):0;}
  function paintPins(){raf=0;layer.replaceChildren();if(!opened)return;for(const n of currentNotes){const e=target(n);if(!e)continue;const r=e.getBoundingClientRect();if(r.width===0||r.bottom<0||r.top>innerHeight)continue;const pin=document.createElement('button');pin.type='button';pin.className='annotation-pin';pin.textContent=String(Number(n.id.slice(1)));pin.setAttribute('aria-label','查看标注'+n.id+' '+n.title);pin.style.left=Math.max(4,r.left-15+scrollX)+'px';pin.style.top=Math.max(scrollY+6,r.top+scrollY+4)+'px';pin.addEventListener('click',()=>locate(n.id,false));layer.append(pin);}}
  function schedule(){if(!raf)raf=requestAnimationFrame(paintPins);}
  function open(v){opened=v;document.body.classList.toggle('annotations-open',v);drawer.hidden=!v;toggle.hidden=v;toggle.setAttribute('aria-expanded',String(v));if(!v){document.querySelectorAll('.annotation-focus').forEach(e=>e.classList.remove('annotation-focus'));toggle.focus({preventScroll:true});}schedule();}
  function locate(id,fromDrawer=true){const n=notes.find(x=>x.id===id);if(!n)return;active=id;document.querySelectorAll('.annotation-note').forEach(x=>x.classList.toggle('is-active',x.dataset.note===id));const e=target(n);if(e){document.querySelectorAll('.annotation-focus').forEach(x=>x.classList.remove('annotation-focus'));e.classList.add('annotation-focus');if(fromDrawer){if(innerWidth<=1100)open(false);e.scrollIntoView({behavior:'smooth',block:'center'});e.classList.add('annotation-focus');}clearTimeout(focusTimer);focusTimer=setTimeout(()=>e.classList.remove('annotation-focus'),4500);}if(!fromDrawer){drawer.querySelector('[data-note="'+id+'"]').scrollIntoView({behavior:'smooth',block:'nearest'});}schedule();}
  function render(){const c=context();currentNotes=notes.filter(n=>c==='modal'?n.modal:n.step===c).filter(n=>target(n));const nav=drawer.querySelector('.annotation-nav');nav.innerHTML=[1,2,3].map(s=>'<button type="button" data-note-step="'+s+'" class="'+(c===s?'active':'')+'">step'+s+'</button>').join('');nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(c==='modal'){const close=$('[data-action="close-modal"]');if(close)close.click();}const tab=$('.steps [data-step="'+b.dataset.noteStep+'"]');if(tab)tab.click();}));
    drawer.querySelector('.annotation-scroll').innerHTML='<p class="annotation-context">'+(c==='modal'?'选择卡券弹窗':c?'step'+c+' 的变更说明':'当前页面')+'</p>'+(currentNotes.length?currentNotes.map(n=>'<section class="annotation-note '+(active===n.id?'is-active':'')+'" data-note="'+n.id+'"><h3><span class="number">'+Number(n.id.slice(1))+'</span>'+n.title+'</h3><p class="refs">'+n.refs+'</p><p>'+n.text+'</p>'+(n.pending?'<p class="pending">'+n.pending+'</p>':'')+'<button type="button" data-locate="'+n.id+'">定位字段</button></section>').join(''):'<p class="annotation-empty">本次调整集中在step1至step3。可用上方导航查看对应标注。</p>');drawer.querySelectorAll('[data-locate]').forEach(b=>b.addEventListener('click',()=>locate(b.dataset.locate)));schedule();}
  toggle.addEventListener('click',()=>{open(true);render();drawer.querySelector('button').focus({preventScroll:true});});drawer.querySelector('.annotation-heading button').addEventListener('click',()=>open(false));drawer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();open(false);}});
  new MutationObserver(render).observe($('#main'),{childList:true,subtree:true});new MutationObserver(render).observe($('#modal-root'),{childList:true,subtree:true});window.addEventListener('scroll',schedule,true);window.addEventListener('resize',schedule);open(opened);render();
})();
